model:
  d_model: 512
  nhead: 8
  num_layers: 6
  dim_feedforward: 2048

training:
  batch_size: 1024
  epochs: 100
  learning_rate: 0.0001
  max_seq_len: 512

data:
  min_char_freq: 3
  chunk_size: 5000